### ISSUE TITLE
Is there any roadmap or todo list of this project?

### ISSUE THREAD

**Issue by PalanQu** [sunary/sqlize#24]
This project is awesome, I use in my own project, is there any roadmap or TODO list? I want to contribute to this project

**Comment by sunary** [comment]
Thanks for your contribution, I’m not sure about the roadmap because I don’t have any idea right now, but still have something TODO:

```
[ ] Use DELETE FROM instead of TRUNCATE for MySQL migrate version (ref: https://github.com/golang-migrate/migrate/pull/656)
[ ] test on PostgreSQL (I’m not ​​familiar with this, so I think something doesn’t worked property)
```

Feel free if you have any ideas.

**Comment by PalanQu** [comment]
Thanks for your information!
