### ISSUE TITLE
Postgres SQL output incorrect.

### ISSUE THREAD

**Issue by facefunk** [sunary/sqlize#29]
Hi,

Very nice project! I discovered sqlize on [a reddit post](https://www.reddit.com/r/golang/comments/llpza9/a_pure_golang_postgresql_parser_powered_by/) while I was looking for a Go SQL parser implementation to incorporate into [pgdiff](https://github.com/facefunk/pgdiff).

Anyway, it seems the Postgres SQL output is currently still in-progress but you've done pretty much all the work already so a trivial fix is possible.

Would you be opposed to [this patch](https://github.com/facefunk/sqlize/commit/114d12b5ba1e2a7b010dbc61d391a96374548386)? It completely fixes the issues for my current use case.

Thanks.

**Comment by sunary** [comment]
Thanks for your contribution,

I'm not familiar with the Postgres SQL so much, feel free if you have any issues with them, let me know or create any PR can fix your issues.

patch merged: https://github.com/sunary/sqlize/pull/30
