### ISSUE TITLE
A very good tool, hoping to support more databases

### ISSUE THREAD

**Issue by liushuai05** [sunary/sqlize#34]
A very good tool, hoping to support SQL Server, SQL ite, and more databases

This information comes from Baidu Translate

**Comment by sunary** [comment]
I'm not familiar with them but will try.

**Comment by the-ebdm** [comment]
Hey @sunary - it doesn't look like you've made any progress on that (I understand, I'm not complaining) - do you mind if I have a stab at creating a PR to handle SQLlite? And I'd do it in an extensible way to open the door to allow for other databases as well. Let me know what you think and I'll have a stab

**Comment by sunary** [comment]
Please feel free to proceed with it.

**Comment by sunary** [comment]
I have performed a refactoring to ensure support for other dialects: https://github.com/sunary/sqlize/pull/42

**Comment by liushuai05** [comment]
> Hey @sunary - it doesn't look like you've made any progress on that (I understand, I'm not complaining) - do you mind if I have a stab at creating a PR to handle SQLlite? And I'd do it in an extensible way to open the door to allow for other databases as well. Let me know what you think and I'll have a stab

This is an exciting answer, yes, I also tried once, but I'm sorry, I failed, you can have a better progress, we are looking forward to your

**Comment by iamwavecut** [comment]
> Hey @sunary - it doesn't look like you've made any progress on that (I understand, I'm not complaining) - do you mind if I have a stab at creating a PR to handle SQLlite? And I'd do it in an extensible way to open the door to allow for other databases as well. Let me know what you think and I'll have a stab

Oh, great! I wish that you really do it. Sqlize looks neat, but lacks the SQLite, definitely.

**Comment by sunary** [comment]
Already support sqlite:

https://github.com/sunary/sqlize/blob/master/options.go#L90
