### ISSUE TITLE
I would like to add the option of automatically adding s to the table name, as well as the support for uppercase identifiers such as primary key/external key

### ISSUE THREAD

**Issue by liushuai05** [sunary/sqlize#35]
I would like to add the option of automatically adding s to the table name, as well as the support for uppercase (adding a hump to snake conversion, which does not affect the original snake writing) for primary key/external identifiers. Our company is currently working with almost all frameworks based on Gorm, and this library table name will automatically add s. If it is necessary to define table names in each model, this is a relatively large project. Thank you very much

This information comes from Baidu Translate

**Comment by sunary** [comment]
Ok @liushuai05 , this feature will be added soon.

**Comment by liushuai05** [comment]
> Ok @liushuai05 , this feature will be added soon.

Thank you for your answer. I have already done this function and created a Chinese readme_ Sh.md, I'll give it to you as PR. Unfortunately, the Github access in China is not very stable, and I'm not sure when I can submit it. You need to wait for a moment

**Comment by sunary** [comment]
https://github.com/sunary/sqlize/pull/36

**Comment by sunary** [comment]
move to new PR: https://github.com/sunary/sqlize/pull/37
