### ISSUE TITLE
Load migration with `genDescription` header using PostgreSQL dialect

### ISSUE THREAD

**Issue by florspag** [sunary/sqlize#54]
Hi, 
I have some issue while parsing the sql migration file while using PostgreSQL dialect. 
The `genDescription` is unparsable.
_panic: at or near "#": syntax error_
If i manually remove the gen description on file it works well. Using /* generate by sqlize */ works too. 
Sounds that postgreSQL does not support the # used by MySQL. 
Using /* */ would be compatible by both. 
Regards 
Florent

**Comment by sunary** [comment]
Thank you for your feedback. The issue has been resolved in the latest version.

**Comment by florspag** [comment]
Awesome thank you!
