### ISSUE TITLE
correct get index using map instead of find in slice

### ISSUE THREAD

**Issue by sunary** [sunary/sqlize#7]
Currently get id in map[string]int is correctness, so I'm finding in slice:

https://github.com/sunary/sqlize/blob/master/element/table.go#L150 and

https://github.com/sunary/sqlize/blob/master/element/table.go#L163

Help me correct this and able get id in map[string]int again.

**Comment by peakle** [comment]
i take this one)

**Comment by peakle** [comment]
https://github.com/sunary/sqlize/pull/8
